### ISSUE TITLE
Decoding sniffed NFC exchanges

### ISSUE THREAD

**Issue by nickludlam** [bvernoux/hydrabus#1]
I've just got hold of the HydraBus + HydraNFC hardware, and I've sniffed my first NDEF record read + write.

With the text file, is there any way I can use a graphical tool to visualise the exchanges? I've looked at Wireshark-NFC, but that expects pcap format files. Would there be an easy way to convert the ascii sniffer output to pcap at all?

**Comment by bvernoux** [comment]
Yes a pcap ng format will be a very nice feature.
I have planned that and need to add it in TODO also any help/suggestions are welcome.
The idea will be to save at end both format .txt and .pcapng with same name

**Comment by stupidlinh** [comment]
I will try to write a piece of code to translate it to pcap.

**Comment by bvernoux** [comment]
Nico has done such work see https://github.com/NicoHub/Wireshark-RFID-dissector
I'm just waiting he release the firmware source code to merge it on hydrafw

**Comment by stupidlinh** [comment]
Cool (y)

**Comment by bvernoux** [comment]
This issue has been moved here https://github.com/bvernoux/hydrafw/issues/23
